### ISSUE TITLE
On-the-fly conversion to subwords in Python

### ISSUE THREAD

**Issue by jbingel** [bheinzerling/bpemb#10]
I don't like having to use SentencePiece offline when getting subword vectors for my Python strings, so I did some searching and found this excellent piece of code on Stackoverflow: https://stackoverflow.com/questions/8870261/how-to-split-text-without-spaces-into-list-of-words

With some very slight adaptations, it lets us convert strings to subwords in Python on the fly. Here's a working example:

    from math import log
 
    words = [l.split()[0] for l in open("en.wiki.bpe.op25000.vocab")]
    wordcost = dict((k, log((i+1)*log(len(words)))) for i,k in enumerate(words))
    maxword = max(len(x) for x in words)

    def infer_spaces(s):
        """Uses dynamic programming to infer the location of spaces in a string
        without spaces."""

        # Find the best match for the i first characters, assuming cost has
        # been built for the i-1 first characters.
        # Returns a pair (match_cost, match_length).
        def best_match(i):
            candidates = enumerate(reversed(cost[max(0, i-maxword):i]))
            return min((c + wordcost.get(s[i-k-1:i], 9e999), k+1) for k,c in candidates)

        # Build the cost array.
        cost = [0]
        for i in range(1,len(s)+1):
            c,k = best_match(i)
            cost.append(c)

        # Backtrack to recover the minimal-cost string.
        out = []
        i = len(s)
        while i>0:
            c,k = best_match(i)
            assert c == cost[i]
            out.append(s[i-k:i])

            i -= k

        return " ".join(reversed(out))

    print(infer_spaces(' this is our house in boomchakalaka'.replace(" ", "▁")))

    >>> ▁this ▁is ▁our ▁house ▁in ▁boom ch ak al aka

You might consider integrating this into this repository.

**Comment by jbingel** [comment]
Btw, another advantage to this is that you won't need the `.model` and `.vocab` files, as you can just directly get the vocabulary from the `KeyedVectors` object (`kv.vocab.keys()`). Eliminates the potential for a key to be present in the vocab but not in the vectors.

**Comment by bheinzerling** [comment]
Thanks, that's a nice, short method. I've added it to the repository.

Recently, the SentencePiece Python wrapper became available on pypi, so another way would be `pip install sentencepiece` and then using the API:

```Python
>>> import sentencepiece as spm
>>> sp = spm.SentencePieceProcessor()
>>> sp.Load("test/test_model.model")
True
>>> sp.EncodeAsPieces("This is a test")
```
