### ISSUE TITLE
How do you learn the Chinese BPE?

### ISSUE THREAD

**Issue by Shuailong** [bheinzerling/bpemb#11]
I am working on a project involving **Chinese** BPE. When I use [sentencepiece](https://github.com/google/sentencepiece) or [subword-nmt](https://github.com/rsennrich/subword-nmt) on Gigawords copus (9.8G, 61,407,548 sentences, 2,660,587,671 chars, 11740 unique chars) , the learning is extremly slow. I checked the source code of `subword-nmt` and found that the bottleneck is at the merge ops. The code also takes hundres Giga bytes of memory. Could you share how do you solve the momory problems and how do you train the **chinese** model?

**Comment by bheinzerling** [comment]
I used sentencepiece, which is quite a bit faster than subword-nmt and doesn't need much RAM. I think training a BPE model with a vocab size of 200000 on Chinese Wikipedia (about 1.1GB of text) took a couple of days, so I wouldn't be surprised if training on all of Chinese Gigaword takes two or three weeks, depending on your hardware.

**Comment by Shuailong** [comment]
@bheinzerling Thanks for your prompt reply!
