### ISSUE TITLE
Train --model_type=unigram

### ISSUE THREAD

**Issue by taku910** [bheinzerling/bpemb#12]
Thank you for making this resource.

It would be nice if we can use the model trained with --model_type=unigram, which is a default mode of sentencepiece.

BPE and Unigram show basically the same BLUE score, but unigram is more flexible and supports subword sampling.
https://arxiv.org/abs/1804.10959

**Comment by bheinzerling** [comment]
Thanks for making sentencepiece!

I'm currently preparing the next version of BPEmb and think having unigram models would be a good idea.

**Comment by utrobinmv** [comment]
the current version already contains the unigram model?
