### ISSUE TITLE
Missing tokens in German model

### ISSUE THREAD

**Issue by maurice-g** [bheinzerling/bpemb#14]
For the german models, there seem to be tokens missing in the vector models (200k merge operations) that are present in the vocab list and sentencepiece models. For example `▁plais`or `auens` are in the vocab but fail to look up in the model.

The number of tokens in the model `len(model.index2word)` returns 185712, while in the vocab list there are 200k entries.

Am I missing something here or is there some miss-match between the training of the sentencepiece tokens / glove vectors?

Great resource otherwise, thanks!

**Comment by maurice-g** [comment]
Great, thanks for the swift reply!

**Comment by bheinzerling** [comment]
This is fixed in the latest version.
