### ISSUE TITLE
Encoder not splitting words into subwords

### ISSUE THREAD

**Issue by SamLynnEvans** [bheinzerling/bpemb#16]
![screen shot 2018-11-26 at 14 44 39](https://user-images.githubusercontent.com/28839356/49021146-e6375680-f189-11e8-8c70-0eb0b11a0428.png)

Running bpemb_en.encode is solely splitting the words by spaces and commas etc., not splitting them into subwords... you guys know what's up? Thanks :)

**Comment by bheinzerling** [comment]
Thanks for noticing, that's a mistake in the example.
If / how a word gets split depends on the vocabulary size. Generally, a smaller vocabulary size will yield a segmentation into many subwords, while a large vocabulary size will result in frequent words not being split:

| vocabulary size | segmentation |
| --- | --- |
| 1000 | ['▁str', 'at', 'f', 'ord'] |
| 3000 |  ['▁str', 'at', 'ford'] |
| 5000 | ['▁str', 'at', 'ford'] |
| 10000 | ['▁strat', 'ford'] |
| 25000 | ['▁stratford'] |
| 50000 | ['▁stratford'] |
| 100000 | ['▁stratford'] |
| 200000 | ['▁stratford'] |

I'll add a better explanation to the website.

**Comment by SamLynnEvans** [comment]
Brilliant, thanks for swift reply!
