### ISSUE TITLE
multilingual text

### ISSUE THREAD

**Issue by rohitsaluja22** [bheinzerling/bpemb#19]
hey, thanks for sharing the code. I am working on the multilingual text. Can I give more than one language to segment words/sentences?

**Comment by bheinzerling** [comment]
All sentencepiece models were trained separately on monolingual corpora, so applying them to multilingual text probably won't give you good results unless the languages are very similar.

If you have access to GPUs, you could give [multilingual BERT](https://github.com/google-research/bert/blob/master/multilingual.md) (or its [pytorch version](https://github.com/huggingface/pytorch-pretrained-BERT)) a try.

**Comment by bheinzerling** [comment]
This is now possible with the new multilingual models: https://nlp.h-its.org/bpemb/multi/
