### ISSUE TITLE
size/source of training corpora

### ISSUE THREAD

**Issue by joemzhao** [bheinzerling/bpemb#21]
Hi, thanks for the nice work!

Just a quick question about the size/source of training corpora -- I am wondering for some low resource languages, e.g., Hakka Chinese, what would be the size of the raw corpus to be splitted into BPEs?

I checked the the Hakka Wikidump, and seems it's pretty small (several MB) https://dumps.wikimedia.org/hakwiki/20190120/
and fastText doesn't have embeddings for Hakka.

If larger corpora were used in your project/paper, I am wondering if it's possible to make them available? It would be very helpful and much appreciated.

thanks!

**Comment by bheinzerling** [comment]
I only used Wikipedia as training corpus and am not aware of any other corpus that offers as many languages. Yes, for many languages the Wikidump is quite small, unfortunately. That's why for those languages we only offer BPE models with small vocab sizes, e.g. only 5k and 10k for Hakka Chinese.
