### ISSUE TITLE
Syntax error while importing

### ISSUE THREAD

**Issue by amansrivastava17** [bheinzerling/bpemb#24]
Some syntax error is occurring while importing.

```SyntaxError: Non-ASCII character '\xe2' in file /home/aman/.local/lib/python2.7/site-packages/bpemb/bpemb.py on line 29, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details```

**Comment by bheinzerling** [comment]
This is a Python 2.7 issue: Non-ASCII characters are not allowed in source files unless you declare an encoding.
Would upgrading to Python 3.7 be an option for you?
Python 2.7 is nearing its end of life (https://pythonclock.org/) and major packages like numpy will also stop supporting it: https://docs.scipy.org/doc/numpy-1.14.2/neps/dropping-python2.7-proposal.html
