### ISSUE TITLE
How do you get the embedding/id for the pad token ?

### ISSUE THREAD

**Issue by derlin** [bheinzerling/bpemb#25]
Hi,
This may be a dummy question, but when creating a `BPEmb` with `add_pad_emb=True`, how do I actually get the padding embedding and what is its ID ? This should maybe figure somewhere in the doc:

```python
from bpemb import BPEmb
bp = BPEmb(lang="en", vs=1000, dim=50, add_pad_emb=True)
print(bp.vs) # prints 1000, was expecting 1000+1 ?
```

Thanks for the great work,
derlin

**Comment by derlin** [comment]
Found it in the gensim doc:

```python
bp.emb['<pad>']
```

It seems to (always ?) be an array of zeros.

**Comment by bheinzerling** [comment]
Hi,
not a dummy question at all. I've added this to the docstring:

> This embedding is initizalized with zeros and appended to the end
        of the embedding matrix. Assuming "bpemb" is a BPEmb instance, the
        padding embedding can be looked up with "bpemb['<pad>']", or
        directly accessed with "bpemb.vectors[-1]".

**Comment by derlin** [comment]
This is perfect, thanks !
