### ISSUE TITLE
most_similar method

### ISSUE THREAD

**Issue by trideeprath** [bheinzerling/bpemb#27]
Using the Readme it's not clear how to use the most_similar functionality. 

`>>> bpemb_en.most_similar("ford")`
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'BPEmb' object has no attribute 'most_similar'

```
>>> bpemb_en.emb.most_similar("ford", topn=5)
[('ley', 0.7945780754089355), ('bury', 0.7869017124176025), ('ton', 0.733354389667511), ('brook', 0.7124956250190735), ('field', 0.7107075452804565)]
```

**Comment by bheinzerling** [comment]
Thanks for reporting this.
I fixed this a while ago in the github repository but forgot to upload a new version to pypi. Will do so soon.
