### ISSUE TITLE
<url> symbol is not kept

### ISSUE THREAD

**Issue by noe** [bheinzerling/bpemb#3]
In `preprocess_text.sh`, URLs are replaced by the &lt;url&gt; symbol, but such a symbol is not contained in the sentencepiece models and is therefore processed as normal text and the result is normally `['_<', 'url', '>']`.

**Comment by bheinzerling** [comment]
Thanks, good catch.

A workaround might be to not replace urls with `<url>` during preprocessing.

The best way to properly fix this is probably to find some one-character rare unicode symbol to represent URLs and retrain the embeddings.

**Comment by bheinzerling** [comment]
This is (finally) fixed in the latest version.
