### ISSUE TITLE
Difference between "en.wiki.bpe.vs50000" and "en.wiki.bpe.op50000"

### ISSUE THREAD

**Issue by caozhen-alex** [bheinzerling/bpemb#32]
Hi,

What's the difference between "en.wiki.bpe.vs50000" and "en.wiki.bpe.op50000" and 'txt' and 'bin'?

Or where can I find the explanation?

Thank you.

**Comment by bheinzerling** [comment]
Files with "op" in the name like "en.wiki.bpe.op50000" are old versions. The ones linked on the BPEmb website and downloaded by the Python library are the newest ("vs") version.

txt and bin are different file formats. txt is plain text, bin is the gensim format.

**Comment by caozhen-alex** [comment]
Many thanks!@bheinzerling
