### ISSUE TITLE
Adding support for own models

### ISSUE THREAD

**Issue by stephantul** [bheinzerling/bpemb#38]
Hi,

First of all, thanks for the great package.
Currently, the only way to use my own models with bpemb is to first load another model, and then assign the `.spm` and `.emb` attributes manually. This is a bit unwieldy.

I am interested in adding a subclass of `BPEmb` that overrides the `__init__` of `BPEmb` and simply accepts paths to an `spm` and `emb` model/file, from which the other attributes (e.g. size/vs) are derived. Is this something you would accept as a PR? Do you see any problems with this approach?

Thanks!
Stéphan

**Comment by bheinzerling** [comment]
Hi,

Thanks for this suggestion! I've added two arguments to `BPEmb.__init__`:

```
    model_file: ``Path'', optional (default = None)
        Path to a custom SentencePiece model file.
    emb_file: ``Path'', optional (default = None)
        Path to a custom embedding file. Supported formats are Word2Vec
        plain text and GenSim binary.
```

Can you checkout the latest commit and let me know if this feature works for you? If yes, I'll update the pypi package as well.

**Comment by stephantul** [comment]
Yep, seems to work! I did some tests and everything gives the correct results. Thanks for the swift reply

**Comment by jameschartouni** [comment]
Can you add a .spm vocabulary to enlarge BPemb's multi-language model? For instance can you add Lebanese vocabulary in addition to the already available MSA, Egyptian and Aramaic?
