### ISSUE TITLE
Subword vectors to word vector

### ISSUE THREAD

**Issue by susmoy-macgill36** [bheinzerling/bpemb#39]
How to get a word vector from subword vectors? By averaging?

**Comment by bheinzerling** [comment]
Yes, averaging is a possible choice, but whether it is the best choice depends on your particular application. Please also see my comment here: https://github.com/bheinzerling/bpemb/issues/29#issuecomment-499333215

**Comment by susmoy-macgill36** [comment]
@bheinzerling Thank you so much, Sir.

**Comment by susmoy-macgill36** [comment]
@bheinzerling  Sir, thank you so much.  

If I apply average operation, should I normalize those subword vectors? I want to use the word vector in the Keras embedding layer.
