### ISSUE TITLE
Converting to lowercase in preprocess_text.sh works only with ascii characters

### ISSUE THREAD

**Issue by pshashk** [bheinzerling/bpemb#4]
You need to replace `tr "[:upper:]" "[:lower:]"` with `sed "s/[[:upper:]]*/\L&/"` in order to get correct output for Unicode.

**Comment by bheinzerling** [comment]
Thanks for this!
I'll add this fix and changes from the other issues and retrain the embeddings.

**Comment by bheinzerling** [comment]
This is (finally) fixed in the latest version.
