### ISSUE TITLE
Number isseue in bpemb

### ISSUE THREAD

**Issue by aimanmutasem** [bheinzerling/bpemb#47]
Dear @bheinzerling

I faced a new challenge with Bpemb, it converts any number to zeros like `(1234)` to `(0000)`, this issue affects negatively in the final BLUE score.

How I can overcome this challenge?

Regards,

**Comment by bheinzerling** [comment]
This is intended behaviour and explained here:

https://github.com/bheinzerling/bpemb/issues/20
