### ISSUE TITLE
Load custom Word2Vec

### ISSUE THREAD

**Issue by Delphine22** [bheinzerling/bpemb#48]
Thanks for this very useful package.
It seems loading custom Word2Vec embeddings is not possible.
With KeyedVectors function, I can't load my custom Word2Vec model (trained on custom data). 
I know I can only load the model.bin with Word2Vec.load function.
Is it possible to add this similar function in order to enable custom model loading?

**Comment by bheinzerling** [comment]
Yes, there is support for loading custom models:

https://github.com/bheinzerling/bpemb/issues/38#issuecomment-604217177
