### ISSUE TITLE
Issues after updating to gensim 4.0.0

### ISSUE THREAD

**Issue by arun5309** [bheinzerling/bpemb#56]
One of the simple example that illustrates this issue is the pieces property of an bpemb.BPEmb instance throws the error "AttributeError: The index2word attribute has been replaced by index_to_key since Gensim 4.0.0.
See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4". 

So, support for gensim 4.0.0 is needed.

**Comment by bheinzerling** [comment]
Thanks for raising this issue. I updated the code and according to the unit tests everything should work with gensim 4.0.0 now. Let me know if you encounter any problem.
