### ISSUE TITLE
Error in URL

### ISSUE THREAD

**Issue by davebulaval** [bheinzerling/bpemb#68]
It appears they have changed the URL from [https://bpemb.h-its.org/multi/multi.wiki.bpe.vs100000.model](https://bpemb.h-its.org/multi/multi.wiki.bpe.vs100000.model) to [https://bpemb.h-its.org/multi/multi/multi.wiki.bpe.vs1000000.model](https://bpemb.h-its.org/multi/multi/multi.wiki.bpe.vs1000000.model) on your server. It causes an error 404.

**Comment by bheinzerling** [comment]
Thanks for reporting this issue! It should be fixed in the latest version.
