### ISSUE TITLE
No question marks in Russian models

### ISSUE THREAD

**Issue by avostryakov** [bheinzerling/bpemb#8]
Why is it so? We have it like in English language in the end of interrogative sentences.

**Comment by bheinzerling** [comment]
Nice catch! The reason for this is that question marks are unusually rare in the Russian edition of Wikipedia. The toolchain I use to train the embeddings filtered out rare characters, but I agree that the question mark should be kept.

I'm planning to train the next version of BPEmb, which will hopefully fix this and other issues.

**Comment by avostryakov** [comment]
Please :)

**Comment by bheinzerling** [comment]
This is (finally) fixed in the latest version.
