### ISSUE TITLE
Comparison to other word vectors

### ISSUE THREAD

**Issue by DonaldTsang** [bheinzerling/bpemb#9]
Is it possible to run a benchmark on the accuracy and "training time" of BPE compared to the word vectors listed in the link below (standardized to using same corpus and 300 dimensions)?  
* PDC and HDC
* LexVec and Word2Vec
* GloVe and FastText  
* (possibly meta-embedding)
Link to original benchmark https://github.com/kudkudak/word-embeddings-benchmarks/wiki
Link to secondary benchmark http://ofey.me/papers/wordrep_acl2015.pdf
Other benchmarks http://www.bigdatalab.ac.cn/benchmark/bm/Domain?domain=Word%20Representation
Other benchmarks https://pdfs.semanticscholar.org/343d/39534682bb7b2eec14f573360877eb80cd59.pdf

**Comment by bheinzerling** [comment]
I'm not planning to do comparisons on word-based benchmarks, but there is now a large-scale multilingual evaluation on two downstream tasks (NER and POS-tagging) available: https://arxiv.org/abs/1906.01569
